### ISSUE TITLE
Cannot load such file -- watir-webdriver/locators/element_locator

### ISSUE THREAD

**Issue by Kirikami** [watir/watir-webdriver#377] opened 2015-10-08 10:49 UTC
After updating to selenium-webdriver v.2.48.0 and watir-webdriver v.0.9 on TeamCity server after running bundle install faced with error "cannot load such file -- watir-webdriver/locators/element_locator (LoadError)".
With selenium-webdriver v.2.48.0 and watir-webdriver v.0.8 all working without problems. 
<img width="1101" alt="screen shot 2015-10-08 at 5 49 13 pm" src="https://cloud.githubusercontent.com/assets/7060987/10364375/f8412daa-6de4-11e5-87c4-fe380ff0e003.png">

**Comment by p0deje** [comment] 2015-10-08 11:40
As you might see, [element_locator](https://github.com/watir/watir-webdriver/blob/master/lib/watir-webdriver/locators/element_locator.rb) is still available in watir-webdriver so it looks like something is wrong in your environment.

```ruby
require 'watir-webdriver/locators/element_locator'
#=> true
Watir::VERSION
#=> "0.9.0"
```

Please provide any additional information. You mentioned TeamCity, but can you reproduce the error locally?

**Comment by Kirikami** [comment] 2015-10-08 12:48
On local still all good, problem only on TeamCity agent
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04.5 LTS
Release:	12.04

I saw that in this requirements nothing changed, but when I trying to install current versions of watir-webdriver and selenium-webdriver this problem appears.
Could you suggest smth? currently I hardcoded watir-webdriver version to 0.8 and with latest selenium-wedriver. All working good.

**Comment by p0deje** [comment] 2015-10-08 14:01
Honestly, I have no idea why this can happen except to load paths somehow being broken. Can you share a script/commands that install watir-webdriver on TeamCity?

**Comment by Kirikami** [comment] 2015-10-08 15:55
Just simple bundle install on agent 


[16:08:53]Step 1/4: Bundle install (Command Line) (7s)
[16:08:53][Step 1/4] Starting: /home/build/BuildAgent/temp/agentTmp/custom_script63429025721987012
[16:08:53][Step 1/4] in directory: /home/build/BuildAgent/work/a538474fce0398b8
[16:08:57][Step 1/4] Fetching gem metadata from https://rubygems.org/...........
[16:08:59][Step 1/4] Fetching version metadata from https://rubygems.org/...
[16:08:59][Step 1/4] Fetching dependency metadata from https://rubygems.org/..
[16:09:00][Step 1/4] Resolving dependencies...
[16:09:00][Step 1/4] Using mimemagic 0.3.0
[16:09:00][Step 1/4] Using mini_portile 0.6.2
[16:09:00][Step 1/4] Using nokogiri 1.6.6.2
[16:09:00][Step 1/4] Using systemu 2.6.5
[16:09:00][Step 1/4] Using macaddr 1.7.1
[16:09:00][Step 1/4] Using uuid 2.3.8
[16:09:00][Step 1/4] Using allure-ruby-adaptor-api 0.6.6
[16:09:00][Step 1/4] Using builder 3.2.2
[16:09:00][Step 1/4] Using diff-lcs 1.2.5
[16:09:00][Step 1/4] Using multi_json 1.11.2
[16:09:00][Step 1/4] Using gherkin 2.12.2
[16:09:00][Step 1/4] Using multi_test 0.1.2
[16:09:00][Step 1/4] Using cucumber 1.3.19
[16:09:00][Step 1/4] Using allure-cucumber 0.4.4
[16:09:00][Step 1/4] Using ffi 1.9.10
[16:09:00][Step 1/4] Using childprocess 0.5.6
[16:09:00][Step 1/4] Using i18n 0.7.0
[16:09:00][Step 1/4] Using faker 1.5.0
[16:09:00][Step 1/4] Using yml_reader 0.5
[16:09:00][Step 1/4] Using data_magic 0.21
[16:09:00][Step 1/4] Using headless 2.2.0
[16:09:00][Step 1/4] Using money 6.6.1
[16:09:00][Step 1/4] Using monetize 1.3.1
[16:09:00][Step 1/4] Using mysql2 0.3.16
[16:09:00][Step 1/4] Using net-ssh 3.0.1
[16:09:00][Step 1/4] Using net-ssh-gateway 1.2.0
[16:09:00][Step 1/4] Using page_navigation 0.9
[16:09:00][Step 1/4] Using rubyzip 1.1.7
[16:09:00][Step 1/4] Using websocket 1.2.2
**[16:09:00][Step 1/4] Using selenium-webdriver 2.48.0
[16:09:00][Step 1/4] Using watir-webdriver 0.9.0**
[16:09:00][Step 1/4] Using page-object 1.0.2
[16:09:00][Step 1/4] Using parallel 1.6.1
[16:09:00][Step 1/4] Using parallel_tests 1.9.0
[16:09:00][Step 1/4] Using require_all 1.3.2
[16:09:00][Step 1/4] Using rspec-support 3.3.0
[16:09:00][Step 1/4] Using rspec-core 3.3.2
[16:09:00][Step 1/4] Using rspec-expectations 3.3.1
[16:09:00][Step 1/4] Using rspec-mocks 3.3.2
[16:09:00][Step 1/4] Using rspec 3.3.0
[16:09:00][Step 1/4] Using test_rail_integration 0.0.9.1
[16:09:00][Step 1/4] Using thor 0.19.1
[16:09:00][Step 1/4] Using bundler 1.9.4
[16:09:00][Step 1/4] Bundle complete! 17 Gemfile dependencies, 43 gems now installed.
[16:09:00][Step 1/4] Use `bundle show [gemname]` to see where a bundled gem is installed.
[16:09:00][Step 1/4] Process exited with code 0
[16:09:00]Step 2/4: Run tests (Command Line) (4s)
[16:09:00][Step 2/4] Starting: /home/build/BuildAgent/temp/agentTmp/custom_script1190525908224267791
[16:09:00][Step 2/4] in directory: /home/build/BuildAgent/work/a538474fce0398b8
[16:09:04][Step 2/4] /home/build/BuildAgent/work/a538474fce0398b8/features/support/utilities/boer.rb:116: warning: duplicated key at line 117 ignored: "codes_checkbox"
[16:09:04][Step 2/4] /var/lib/gems/2.2.0/gems/selenium-webdriver-2.48.0/lib/selenium/webdriver/common/w3c_error.rb:183: warning: already initialized constant Selenium::WebDriver::Error::NoAlertPresentError
[16:09:04][Step 2/4] /var/lib/gems/2.2.0/gems/selenium-webdriver-2.48.0/lib/selenium/webdriver/common/error.rb:129: warning: previous definition of NoAlertPresentError was here
[16:09:04][Step 2/4] /var/lib/gems/2.2.0/gems/selenium-webdriver-2.48.0/lib/selenium/webdriver/common/w3c_error.rb:184: warning: already initialized constant Selenium::WebDriver::Error::ScriptTimeOutError
[16:09:04][Step 2/4] /var/lib/gems/2.2.0/gems/selenium-webdriver-2.48.0/lib/selenium/webdriver/common/error.rb:135: warning: previous definition of ScriptTimeOutError was here
**[16:09:04][Step 2/4] cannot load such file -- watir-webdriver/locators/element_locator (LoadError)**
[16:09:04][Step 2/4] /var/lib/gems/2.2.0/gems/watir-webdriver-0.9.0/lib/watir-webdriver.rb:13:in `require'
[16:09:04][Step 2/4] /var/lib/gems/2.2.0/gems/watir-webdriver-0.9.0/lib/watir-webdriver.rb:13:in `<top (required)>'
[16:09:04][Step 2/4] /home/build/BuildAgent/work/a538474fce0398b8/features/support/hooks.rb:1:in `require'
[16:09:04][Step 2/4] /home/build/BuildAgent/work/a538474fce0398b8/features/support/hooks.rb:1:in `<top (required)>'
[16:09:04][Step 2/4] /var/lib/gems/2.2.0/gems/cucumber-1.3.19/lib/cucumber/rb_support/rb_language.rb:95:in `load'
[16:09:04][Step 2/4] /var/lib/gems/2.2.0/gems/cucumber-1.3.19/lib/cucumber/rb_support/rb_language.rb:95:in `load_code_file'
[16:09:04][Step 2/4] /var/lib/gems/2.2.0/gems/cucumber-1.3.19/lib/cucumber/runtime/support_code.rb:180:in `load_file'
[16:09:04][Step 2/4] /var/lib/gems/2.2.0/gems/cucumber-1.3.19/lib/cucumber/runtime/support_code.rb:83:in `block in load_files!'
[16:09:04][Step 2/4] /var/lib/gems/2.2.0/gems/cucumber-1.3.19/lib/cucumber/runtime/support_code.rb:82:in `each'
[16:09:04][Step 2/4] /var/lib/gems/2.2.0/gems/cucumber-1.3.19/lib/cucumber/runtime/support_code.rb:82:in `load_files!'
[16:09:04][Step 2/4] /var/lib/gems/2.2.0/gems/cucumber-1.3.19/lib/cucumber/runtime.rb:184:in `load_step_definitions'
[16:09:04][Step 2/4] /var/lib/gems/2.2.0/gems/cucumber-1.3.19/lib/cucumber/runtime.rb:42:in `run!'
[16:09:04][Step 2/4] /var/lib/gems/2.2.0/gems/cucumber-1.3.19/lib/cucumber/cli/main.rb:47:in `execute!'
[16:09:04][Step 2/4] /var/lib/gems/2.2.0/gems/cucumber-1.3.19/bin/cucumber:13:in `<top (required)>'
[16:09:04][Step 2/4] /usr/local/bin/cucumber:23:in `load'
[16:09:04][Step 2/4] /usr/local/bin/cucumber:23:in `<main>'

**Comment by titusfortner** [comment] 2015-10-08 16:08
Weird, I don't see any reason element_locator wouldn't load since it isn't the first thing that gets loaded. Can you see if your code works in either of the following:
'selenium-webdriver', '2.47.1' && 'watir-webdriver', '0.9.0'
and
'selenium-webdriver', '2.48.0' && 'watir-webdriver', '0.8.0'

**Comment by Kirikami** [comment] 2015-10-09 01:51
'selenium-webdriver', '2.47.1' && 'watir-webdriver', '0.9.0' same problem on TeamCity, ok on local
'selenium-webdriver', '2.48.0' && 'watir-webdriver', '0.8.0' all working good on all envs. 
Thank you.

**Comment by p0deje** [comment] 2015-10-09 04:09
It says `Starting: /home/build/BuildAgent/temp/agentTmp/custom_script1190525908224267791`. What are the contents of this script?

**Comment by Kirikami** [comment] 2015-10-09 08:02
bundle install thats all what in script, execution in command line.

**Comment by p0deje** [comment] 2015-10-09 14:08
bundle install works correctly, but then you run something else which fails with this error. What exactly do you run?

**Comment by Kirikami** [comment] 2015-10-10 04:28
Cucumber test "xvfb-run -s "-screen 0 1920x1080x16" bundle exec cucumber -r features features/ -p my.local --expand -f Teamcity::Cucumber::Formatter -f AllureCucumber::Formatter --out allureoutput.log "

**Comment by p0deje** [comment] 2015-10-10 09:34
Well, this didn't make it more clear.

With that said, if there is any way you could make it reproduce locally so it can be debugged, let us know. For now, it seems like not a watir-webdriver issue but rather a problem with TeamCity environment, so I'm closing it.

**Closed by p0deje** 2015-10-10 09:34 UTC

**Comment by tjdurden** [comment] 2015-11-23 09:12
@p0deje - Not a TeamCity issue. We're seeing this on local dev envs, as well as when triggering via Jenkins (running via slave).

**Comment by p0deje** [comment] 2015-11-23 09:19
@tjdurden Please upgrade to latest version of watir-webdriver, it's fixed.

**Comment by tjdurden** [comment] 2015-12-15 11:38
Hi @p0deje - I'm still seeing this:

```
/Library/Ruby/Gems/2.0.0/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/common/w3c_error.rb:183: warning: already initialized constant Selenium::WebDriver::Error::NoAlertPresentError
/Library/Ruby/Gems/2.0.0/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/common/error.rb:129: warning: previous definition of NoAlertPresentError was here
/Library/Ruby/Gems/2.0.0/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/common/w3c_error.rb:184: warning: already initialized constant Selenium::WebDriver::Error::ScriptTimeOutError
/Library/Ruby/Gems/2.0.0/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/common/error.rb:135: warning: previous definition of ScriptTimeOutError was here
```

Any ideas?

Using watir-webdriver 0.9.1, selenium-webdriver 2.48.1

**Comment by p0deje** [comment] 2015-12-15 11:39
@tjdurden These are just warnings, so you can ignore them (though they should still be fixed).

**Comment by tjdurden** [comment] 2015-12-15 12:18
Agreed, but it's clutter. A fix would be appreciated. Cheers.
