### ISSUE TITLE
Can't get the content generated by ajax response

### ISSUE THREAD

**Issue by gaoguoxin** [watir/watir-webdriver#320] opened 2015-02-26 02:37 UTC
bellow is my code and the content is what I want  which was generated by ajax response,without the headless I can got it 
```ruby
require 'nokogiri'
require 'watir-webdriver'

browser = Watir::Browser.new 
browser.goto 'http://www.tudou.com/albumplay/2Dk1-JIVpzo/yp927-uKGMs.html?FR=LIAN'
sleep(5)
doc = Nokogiri::HTML(browser.html)
content = doc.css(".dig_container .num")
puts '-------------------------------------'
puts content.inspect
puts '-------------------------------------'
browser.close
```

but on the server of ubuntu  I have to use headless ,so my code is 
```ruby
require 'nokogiri'
require 'watir-webdriver'
require 'headless'

headless = Headless.new 
headless.start

browser = Watir::Browser.new
browser.goto 'http://www.tudou.com/albumplay/2Dk1-JIVpzo/yp927-uKGMs.html?FR=LIAN'

until browser.element(:css => "#digBury .dig_container").exists? do 
	puts '********sleeping *************'
	sleep 1 
end

doc = Nokogiri::HTML(browser.html)
content = doc.css("#digBury .dig_container")

puts '-------------------------------------'
puts content.inspect
puts '-------------------------------------'

browser.close

headless.destroy
```

Unlucky，I got an empty array  is there something wrong with my code?

**Comment by ajanckila** [comment] 2015-02-26 02:54
Try browser.element(:css => "#digBury .dig_container").wait_until_present

Instead

In your first example
content = doc.css(".dig_container .num")

That would execute immediately ( before the AJAX process finishes and that
element is created in the DOM which is why you're seeing an empty array.

The wait_until_present will timeout at default - 30 seconds.

You can also do

Watir::Wait.until(15){ browser.element(selector) }

To adjust the time to wait or set the watir timeout globally in
configuration.

For confirmation modals or anything else you expect to disappear there is
wait_while_present

**Comment by ajanckila** [comment] 2015-02-26 03:05
I would also double check the selector path not sure if you need to use an
ID and a class try just using ID and the specific ID if it is the only one
on the page or remove the space between the dot and the end of the ID name.

If dig container is nested in the outside dig Bury div:

dig_container = B.element (id: "digBury).element(css: ". dig-container")

Even better if you know the element

dig_container = B.div(id: "digBury).div(css: ". dig-container")

nums = dig_container. elements(css: ". nums)

**Comment by gaoguoxin** [comment] 2015-02-26 05:01
@ajanckila if the 
```ruby
content = doc.css(".dig_container .num")
```
 would execute immediately ,I will not get the result but in fact  I got the result with the following code:
```ruby
require 'nokogiri'
require 'watir-webdriver'

browser = Watir::Browser.new 
browser.goto 'http://www.tudou.com/albumplay/2Dk1-JIVpzo/yp927-uKGMs.html?FR=LIAN'
browser.element(:css => "#digBury .dig_container").wait_until_present
doc = Nokogiri::HTML(browser.html)
content = doc.css(".dig_container .num")
puts '-------------------------------------'
puts content.inspect
puts '-------------------------------------'
browser.close
```
and the result is
```ruby
[#<Nokogiri::XML::Element:0x3fdd3a69d9c4 name="span" attributes=[#<Nokogiri::XML::Attr:0x3fdd3a69d910 name="class" value="num">] children=[#<Nokogiri::XML::Text:0x3fdd3a69d2e4 "332">]>]
```

On the other hand ,when I use the headless on my ubuntu server,I failed
```ruby
require 'nokogiri'
require 'watir-webdriver'
require 'headless'

headless = Headless.new 
headless.start

browser = Watir::Browser.new 
browser.goto 'http://www.tudou.com/albumplay/2Dk1-JIVpzo/yp927-uKGMs.html?FR=LIAN'
browser.element(:css => "#digBury .dig_container").wait_until_present
doc = Nokogiri::HTML(browser.html)
content = doc.css(".dig_container .num")
puts '-------------------------------------'
puts content.inspect
puts '-------------------------------------'
browser.close
headless.destroy
```
and I got an empty array . The diffrence between these codes is the headless on the server,it seems that when I use the headless the code 
```ruby
content = doc.css(".dig_container .num")
```
will be executed immediately,and I got an error 
```ruby
Watir::Wait::TimeoutError: timed out after 30 seconds, waiting for {:css=>"#digBury .dig_container"} to become present
```

**Comment by p0deje** [comment] 2015-02-26 05:43
Trying to print `browser.html` at first and see if it's any different with/without headless. It might show what the problem is.

Also, you can try to make a screenshot with `browser.screenshot.save` - that might help as well.

In any case, this is not a bug in watir so I'm closing this. You can get help at [google group](http://groups.google.com/group/watir-general/).

**Closed by p0deje** 2015-02-26 05:43 UTC
