### ISSUE TITLE
The value set by input field is not retaining.

### ISSUE THREAD

**Issue by shanth** [watir/watir-webdriver#417] opened 2016-03-30 07:49 UTC
I am using watir-webdriver to set an input field which accepts the date format.
The below method is setting the value but the filed is not retaining and showing the default value.
ie.text_field(:name, 'date from').set('25/03/16')

Versions used: watir-webdriver0.9.1
Ruby2.0.0

Below is the html code for the input feild and above method is working fine with watir.
<input name="form:context:dateFromInputDate" class="rf-cal-inp dateStringInput" id="form:context:dateFromInputDate" style="vertical-align: middle;" onchange='RichFaces.ajax(this,event,{"parameters":{"javax.faces.behavior.event":"inputchange","org.richfaces.ajax.component":"form:context:dateFrom"} ,"sourceId":this} )' type="text" value="30/03/16">

**Comment by p0deje** [comment] 2016-03-30 09:18
Please provide [concise reproducible test case](http://sscce.org/) so that we could act on this issue.

**Comment by shanth** [comment] 2016-03-30 11:00
I can't give the reproducible application code as it is build on JSF and,AJAX  other technologies.
The application have the text field and it have calendar icon. By default the input field shows the current date.The user can enter date into text field or can select from calendar.

I tried to reproduce on some external application but it is giving below errror when try to open the application using IE watir webdriver.

url: http://example.irian.at/myfacesexamples/calendar.jsf

Ruby code: 
client = Selenium::WebDriver::Remote::Http::Default.new
client.timeout = 60
browser  = Watir::Browser.new :ie,:http_client => client

Error:
:/Ruby200/lib/ruby/2.0.0/net/protocol.rb:158:in `rescue in rbuf_fill': Net::ReadTimeout (Net::ReadTimeout)
	from c:/Ruby200/lib/ruby/2.0.0/net/protocol.rb:152:in `rbuf_fill'
	from c:/Ruby200/lib/ruby/2.0.0/net/protocol.rb:134:in `readuntil'
	from c:/Ruby200/lib/ruby/2.0.0/net/protocol.rb:144:in `readline'

**Comment by shanth** [comment] 2016-03-30 11:40
As mentioned in issue#295, the date file issue got resolve by replacing set method with send_keys.
ie.text_field(:name, 'date from').when_present.send_keys [:control,'a'],:delete,dateFrom.
Can anyone the problem with set method and rbuf_fill': Net::ReadTimeout  error?

**Comment by p0deje** [comment] 2016-03-31 08:55
`Net::ReadTimeout` comes from Selenium. I'm not sure what exactly causes it, but that's definitely environment issue.

Closing this as duplicate of #295.

**Closed by p0deje** 2016-03-31 08:55 UTC
